import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { categories, getRecipe } from "@/lib/content";
const Field = ({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) => <label className="grid gap-2 text-sm font-bold">{label}{children}{hint && <span className="text-xs font-normal text-[#708178]">{hint}</span>}</label>;
export function RecipeForm({ recipeSlug }: { recipeSlug?: string }) { const recipe = recipeSlug ? getRecipe(recipeSlug) : undefined; return <form className="grid gap-7"><section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Recipe details</h2><Field label="Title"><Input name="title" defaultValue={recipe?.title} required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Slug" hint="Lowercase words separated by hyphens"><Input name="slug" defaultValue={recipe?.slug} required /></Field><Field label="Status"><select name="status" defaultValue={recipe?.status ?? "draft"} className="focus-ring h-11 rounded-lg border border-[#cbd9cf] bg-white px-3"><option value="draft">Draft</option><option value="published">Published</option></select></Field></div><Field label="Short description"><Textarea name="description" defaultValue={recipe?.description} /></Field><Field label="Hero image URL"><Input type="url" name="hero_image_url" defaultValue={recipe?.image} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Category"><select name="category" defaultValue={recipe?.category.slug} className="focus-ring h-11 rounded-lg border border-[#cbd9cf] bg-white px-3">{categories.map(c => <option key={c.slug} value={c.slug}>{c.name}</option>)}</select></Field><Field label="Tags" hint="Comma-separated"><Input name="tags" defaultValue={recipe?.tags.join(", ")} /></Field></div></section>
<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Times and nutrition</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Prep minutes"><Input type="number" min="0" name="prep_minutes" defaultValue={recipe?.prepMinutes} /></Field><Field label="Cook minutes"><Input type="number" min="0" name="cook_minutes" defaultValue={recipe?.cookMinutes} /></Field><Field label="Servings"><Input type="number" min="1" name="servings" defaultValue={recipe?.servings} /></Field><Field label="Calories"><Input type="number" min="0" name="calories" defaultValue={recipe?.calories} /></Field><Field label="Protein (g)"><Input type="number" min="0" name="protein" defaultValue={recipe?.protein} /></Field><Field label="Carbs (g)"><Input type="number" min="0" name="carbs" defaultValue={recipe?.carbs} /></Field><Field label="Fat (g)"><Input type="number" min="0" name="fat" defaultValue={recipe?.fat} /></Field></div></section>
<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Recipe content</h2><Field label="Ingredients" hint="One ingredient per line"><Textarea name="ingredients" className="min-h-52" defaultValue={recipe?.ingredients.join("\n")} /></Field><Field label="Instructions" hint="One step per line"><Textarea name="instructions" className="min-h-52" defaultValue={recipe?.instructions.join("\n")} /></Field><Field label="Helpful tips" hint="One tip per line"><Textarea name="tips" defaultValue={recipe?.tips.join("\n")} /></Field><Field label="FAQs" hint="Enter one question and answer pair per line, separated by |"><Textarea name="faqs" defaultValue={recipe?.faqs.map(f => `${f.question} | ${f.answer}`).join("\n")} /></Field></section>
<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Search appearance</h2><Field label="SEO title"><Input name="seo_title" maxLength={70} defaultValue={recipe?.seoTitle} /></Field><Field label="Meta description"><Textarea name="meta_description" maxLength={170} defaultValue={recipe?.metaDescription} /></Field></section><div className="flex justify-end gap-3"><Button type="button" variant="outline">Save draft</Button><Button type="submit">{recipe ? "Update recipe" : "Create recipe"}</Button></div></form> }
