"use client";
import Image from "next/image";
import { useActionState, useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { saveRecipe, uploadRecipeImage, type ActionState } from "@/app/admin/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Recipe } from "@/types/content";
import type { AdminCategory } from "@/lib/admin-data";
const initial: ActionState = { ok: false, message: "" };
const Field = ({ label, children, error, hint }: { label: string; children: React.ReactNode; error?: string; hint?: string }) => <label className="grid gap-2 text-sm font-bold">{label}{children}{error ? <span className="text-xs text-red-700">{error}</span> : hint ? <span className="text-xs font-normal text-[#708178]">{hint}</span> : null}</label>;
function ListEditor({ label, name, initialItems, placeholder }: { label: string; name: string; initialItems: string[]; placeholder: string }) { const [items, setItems] = useState(initialItems.length ? initialItems : [""]); const move = (i: number, d: number) => setItems(current => { const copy=[...current]; [copy[i],copy[i+d]]=[copy[i+d],copy[i]]; return copy; }); return <fieldset><legend className="mb-2 text-sm font-bold">{label}</legend><input type="hidden" name={name} value={items.join("\n")} /><div className="grid gap-2">{items.map((item,i) => <div className="grid grid-cols-[1fr_auto] gap-2" key={i}><Input aria-label={`${label} ${i+1}`} value={item} placeholder={placeholder} onChange={e => setItems(v => v.map((x,n) => n===i ? e.target.value : x))} /><div className="flex"><button type="button" aria-label="Move up" disabled={!i} onClick={() => move(i,-1)} className="p-2 disabled:opacity-30"><ArrowUp size={16}/></button><button type="button" aria-label="Move down" disabled={i===items.length-1} onClick={() => move(i,1)} className="p-2 disabled:opacity-30"><ArrowDown size={16}/></button><button type="button" aria-label="Remove" onClick={() => setItems(v => v.length===1 ? [""] : v.filter((_,n)=>n!==i))} className="p-2 text-red-700"><Trash2 size={16}/></button></div></div>)}</div><Button type="button" variant="outline" size="sm" className="mt-3" onClick={() => setItems(v => [...v,""])}><Plus size={15}/> Add</Button></fieldset> }
function ImageUploader({ value, onChange }: { value: string; onChange: (v:string)=>void }) { const [state, action, pending] = useActionState(uploadRecipeImage, initial); useEffect(() => { if (state.imageUrl) onChange(state.imageUrl); }, [state.imageUrl, onChange]); return <div className="grid gap-3"><input type="hidden" name="hero_image_url" value={value}/>{value && <Image src={value} alt="Recipe preview" width={360} height={220} className="aspect-[8/5] rounded-xl object-cover" />}<div className="flex flex-wrap items-center gap-3"><Input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/avif" className="max-w-sm pt-2"/><Button type="submit" formAction={action} variant="outline" disabled={pending}>{pending ? "Uploading…" : "Upload image"}</Button></div>{state.message && <p className={`text-xs ${state.ok ? "text-green-700" : "text-red-700"}`}>{state.message}</p>}</div> }
export function RecipeForm({ recipe, categories }: { recipe?: Recipe; categories: AdminCategory[] }) { const [state, action, pending] = useActionState(saveRecipe, initial); const [image, setImage] = useState(recipe?.image || ""); return <form action={action} className="grid gap-7"><input type="hidden" name="id" value={recipe?.id || ""}/><input type="hidden" name="old_slug" value={recipe?.slug || ""}/>{state.message && <p role="status" className="rounded-lg bg-red-50 p-3 text-sm font-bold text-red-800">{state.message}</p>}<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Recipe details</h2><Field label="Title" error={state.errors?.title}><Input name="title" defaultValue={recipe?.title} required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Slug" error={state.errors?.slug}><Input name="slug" defaultValue={recipe?.slug} required /></Field><Field label="Status"><select name="status" defaultValue={recipe?.status ?? "draft"} className="focus-ring h-11 rounded-lg border border-[#cbd9cf] bg-white px-3"><option value="draft">Draft</option><option value="published">Published</option></select></Field></div><Field label="Short description" error={state.errors?.description}><Textarea name="description" defaultValue={recipe?.description} /></Field><Field label="Hero image"><ImageUploader value={image} onChange={setImage}/></Field><Field label="Image alt text"><Input name="image_alt" defaultValue={recipe?.imageAlt}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Category"><select name="category" defaultValue={categories.find(c=>c.slug===recipe?.category.slug)?.id} className="focus-ring h-11 rounded-lg border border-[#cbd9cf] bg-white px-3">{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Tags"><Input name="tags" defaultValue={recipe?.tags.join(", ")} /></Field></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="featured" defaultChecked={recipe?.featured}/> Feature on homepage</label></section>
<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Times and nutrition</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Prep minutes","prep_minutes",recipe?.prepMinutes],["Cook minutes","cook_minutes",recipe?.cookMinutes],["Servings","servings",recipe?.servings],["Calories","calories",recipe?.calories],["Protein (g)","protein",recipe?.protein],["Carbs (g)","carbs",recipe?.carbs],["Fat (g)","fat",recipe?.fat]].map(([label,name,value])=><Field key={String(name)} label={String(label)}><Input type="number" min="0" name={String(name)} defaultValue={value}/></Field>)}</div></section>
<section className="grid gap-6 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Recipe content</h2><ListEditor label="Ingredients" name="ingredients" initialItems={recipe?.ingredients || []} placeholder="1 cup quinoa, rinsed"/><ListEditor label="Instructions" name="instructions" initialItems={recipe?.instructions || []} placeholder="Heat the oven to 425°F…"/><ListEditor label="FAQs (question | answer)" name="faqs" initialItems={recipe?.faqs.map(f=>`${f.question} | ${f.answer}`)||[]} placeholder="Can I make this ahead? | Yes…"/><Field label="Helpful tips" hint="One tip per line"><Textarea name="tips" defaultValue={recipe?.tips.join("\n")} /></Field></section>
<section className="grid gap-5 rounded-xl border border-[#dce3dd] bg-white p-6"><h2 className="text-lg font-bold">Search appearance</h2><Field label="SEO title"><Input name="seo_title" maxLength={70} defaultValue={recipe?.seoTitle} /></Field><Field label="Meta description"><Textarea name="meta_description" maxLength={170} defaultValue={recipe?.metaDescription} /></Field></section><div className="flex justify-end"><Button type="submit" disabled={pending}>{pending ? "Saving…" : recipe ? "Update recipe" : "Create recipe"}</Button></div></form> }
