import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Clock, UtensilsCrossed } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RecipeCard } from "@/components/recipes/recipe-card";
import { SectionHeading } from "@/components/recipes/section-heading";
import { getCategories, getFeaturedRecipes, getLatestRecipes, getPublishedRecipes } from "@/lib/queries";

export default async function HomePage() { const [categories, recipes, featuredRecipes, latest] = await Promise.all([getCategories(), getPublishedRecipes(), getFeaturedRecipes(1), getLatestRecipes(3)]); const featured = featuredRecipes[0]; if (!featured) return <section className="container-site py-24"><h1 className="display text-6xl font-bold">Fresh recipes are coming soon.</h1></section>; return <>
  <section className="bg-[#f1f5ed] py-8 sm:py-12"><div className="container-site grid overflow-hidden rounded-[2rem] bg-[#dcebdc] lg:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-center px-7 py-12 sm:px-12 lg:px-16"><p className="eyebrow">Fresh, filling & weeknight-ready</p><h1 className="display mt-5 text-5xl font-bold sm:text-6xl lg:text-7xl">Healthy food you’ll actually crave.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#476158]">Flavor-first recipes made with everyday ingredients, sensible nutrition, and clear, tested steps.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href={`/recipes/${featured.slug}`}>Cook the featured recipe <ArrowRight size={18} /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/recipes">Browse all recipes</Link></Button></div></div><Link href={`/recipes/${featured.slug}`} className="relative min-h-[380px] lg:min-h-[600px]"><Image src={featured.image} alt={featured.imageAlt} fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover" /><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-white/95 p-5 shadow-xl backdrop-blur"><p className="eyebrow">Editor’s pick</p><h2 className="display mt-1 text-2xl font-bold">{featured.title}</h2><p className="mt-2 flex items-center gap-2 text-xs font-bold text-[#5b7166]"><Clock size={15} /> {featured.prepMinutes + featured.cookMinutes} minutes · {featured.protein}g protein</p></div></Link></div></section>
  <section className="container-site py-20"><SectionHeading eyebrow="Reader favorites" title="Popular healthy recipes" /><div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{recipes.slice(0, 3).map((r, i) => <RecipeCard key={r.slug} recipe={r} priority={i < 2} />)}</div></section>
  <section className="bg-[#f7f6ef] py-20"><div className="container-site"><SectionHeading eyebrow="Find your next meal" title="Browse by category" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category, i) => <Link key={category.slug} href={`/categories/${category.slug}`} className="focus-ring group flex min-h-40 flex-col justify-between rounded-2xl border border-[#dde4d8] bg-white p-6 hover:border-[#75a98a]"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e0f1e4] text-[#287a55]"><UtensilsCrossed size={18} /></span><div><h3 className="display text-2xl font-bold">{category.name}</h3><p className="mt-1 text-sm text-[#687a71]">{i + 5} recipes <ArrowRight className="ml-1 inline transition group-hover:translate-x-1" size={14} /></p></div></Link>)}</div></div></section>
  <section className="container-site py-20"><SectionHeading eyebrow="New this week" title="Latest from our kitchen" /><div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{latest.map((r) => <RecipeCard key={r.slug} recipe={r} />)}</div></section>
  <section className="container-site grid gap-6 pb-10 lg:grid-cols-2"><div className="rounded-3xl bg-[#1f5c41] p-8 text-white sm:p-12"><p className="eyebrow !text-[#bce8ca]">Strong & satisfying</p><h2 className="display mt-3 text-4xl font-bold">High-protein favorites</h2><p className="mt-4 max-w-md leading-7 text-[#d8eadf]">Balanced recipes that make hitting your protein goals deliciously simple.</p><Button asChild className="mt-7 bg-white text-[#1f5c41] hover:bg-[#edf6ef]"><Link href="/categories/high-protein">Explore recipes</Link></Button></div><div className="rounded-3xl bg-[#f1dfb8] p-8 sm:p-12"><p className="eyebrow">On the table fast</p><h2 className="display mt-3 text-4xl font-bold">Quick healthy dinners</h2><p className="mt-4 max-w-md leading-7 text-[#59665b]">Low-fuss, full-flavor meals for the nights when time is tight.</p><Button asChild className="mt-7"><Link href="/categories/quick-dinners">Dinner in 30</Link></Button></div></section>
  </> }
