"use server";
import { revalidatePath, revalidateTag } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { isValidSlug, validateRecipeInput } from "@/lib/validation";

export type ActionState = { ok: boolean; message: string; errors?: Record<string, string>; imageUrl?: string };
const lines = (value: FormDataEntryValue | null) => String(value ?? "").split("\n").map(v => v.trim()).filter(Boolean);
const slugify = (v: string) => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
function refresh(slug?: string, categories: string[] = []) { revalidateTag("recipes"); revalidateTag("categories"); revalidatePath("/"); revalidatePath("/recipes"); revalidatePath("/sitemap.xml"); if (slug) revalidatePath(`/recipes/${slug}`); categories.forEach(c => revalidatePath(`/categories/${c}`)); }

export async function saveRecipe(_state: ActionState, formData: FormData): Promise<ActionState> {
  const admin = await requireAdmin(); const input = Object.fromEntries(formData.entries()); const validation = validateRecipeInput(input); if (!validation.valid) return { ok: false, message: "Please correct the highlighted fields.", errors: validation.errors };
  const supabase = await createClient(); const id = String(formData.get("id") || ""); const oldSlug = String(formData.get("old_slug") || ""); const status = String(formData.get("status")) === "published" ? "published" : "draft"; const now = new Date().toISOString();
  const row = { title: String(formData.get("title")).trim(), slug: String(formData.get("slug")).trim(), short_description: String(formData.get("description")).trim(), hero_image_url: String(formData.get("hero_image_url") || "") || null, hero_image_alt: String(formData.get("image_alt") || formData.get("title")), author_id: admin.user.id, author_name: String(formData.get("author_name") || admin.profile.display_name || admin.user.email || "FreshTable Team"), status, published_at: status === "published" ? String(formData.get("published_at") || now) : null, prep_minutes: Number(formData.get("prep_minutes") || 0), cook_minutes: Number(formData.get("cook_minutes") || 0), servings: Number(formData.get("servings") || 1), calories: Number(formData.get("calories") || 0), protein_grams: Number(formData.get("protein") || 0), carbs_grams: Number(formData.get("carbs") || 0), fat_grams: Number(formData.get("fat") || 0), helpful_tips: lines(formData.get("tips")), seo_title: String(formData.get("seo_title") || "") || null, meta_description: String(formData.get("meta_description") || "") || null, featured: formData.get("featured") === "on" };
  const result = id ? await supabase.from("recipes").update(row).eq("id", id).select("id").single() : await supabase.from("recipes").insert(row).select("id").single();
  if (result.error) return { ok: false, message: result.error.message }; const recipeId = result.data.id;
  await Promise.all([supabase.from("ingredients").delete().eq("recipe_id", recipeId), supabase.from("recipe_steps").delete().eq("recipe_id", recipeId), supabase.from("recipe_faqs").delete().eq("recipe_id", recipeId), supabase.from("recipe_categories").delete().eq("recipe_id", recipeId), supabase.from("recipe_tags").delete().eq("recipe_id", recipeId)]);
  const ingredientRows = lines(formData.get("ingredients")).map((display_text, sort_order) => ({ recipe_id: recipeId, display_text, sort_order }));
  const stepRows = lines(formData.get("instructions")).map((instruction, sort_order) => ({ recipe_id: recipeId, instruction, sort_order }));
  const faqRows = lines(formData.get("faqs")).map((value, sort_order) => { const [question, ...answer] = value.split("|"); return { recipe_id: recipeId, question: question.trim(), answer: answer.join("|").trim(), sort_order }; }).filter(f => f.question && f.answer);
  if (ingredientRows.length) await supabase.from("ingredients").insert(ingredientRows); if (stepRows.length) await supabase.from("recipe_steps").insert(stepRows); if (faqRows.length) await supabase.from("recipe_faqs").insert(faqRows);
  const categoryId = String(formData.get("category") || ""); if (categoryId) await supabase.from("recipe_categories").insert({ recipe_id: recipeId, category_id: categoryId, is_primary: true });
  const tagNames = String(formData.get("tags") || "").split(",").map(v => v.trim()).filter(Boolean); for (const name of tagNames) { const { data: tag } = await supabase.from("tags").upsert({ name, slug: slugify(name) }, { onConflict: "slug" }).select("id").single(); if (tag) await supabase.from("recipe_tags").insert({ recipe_id: recipeId, tag_id: tag.id }); }
  refresh(row.slug, [String(formData.get("category_slug") || "")]); if (oldSlug && oldSlug !== row.slug) revalidatePath(`/recipes/${oldSlug}`); redirect(`/admin?success=${id ? "updated" : "created"}`);
}
export async function deleteRecipe(formData: FormData) { await requireAdmin(); const id = String(formData.get("id")); const slug = String(formData.get("slug")); const supabase = await createClient(); const { error } = await supabase.from("recipes").delete().eq("id", id); if (error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); refresh(slug); redirect("/admin?success=deleted"); }
export async function saveCategory(_state: ActionState, formData: FormData): Promise<ActionState> { await requireAdmin(); const name = String(formData.get("name") || "").trim(); const slug = String(formData.get("slug") || "").trim(); if (!name || !isValidSlug(slug)) return { ok: false, message: "Enter a name and a valid lowercase slug." }; const supabase = await createClient(); const id = String(formData.get("id") || ""); const query = id ? supabase.from("categories").update({ name, slug, description: String(formData.get("description") || "") }).eq("id", id) : supabase.from("categories").insert({ name, slug, description: String(formData.get("description") || "") }); const { error } = await query; if (error) return { ok: false, message: error.message }; refresh(undefined, [slug]); return { ok: true, message: id ? "Category updated." : "Category created." }; }
export async function deleteCategory(formData: FormData) { await requireAdmin(); const id = String(formData.get("id")); const supabase = await createClient(); const { count } = await supabase.from("recipe_categories").select("recipe_id", { count: "exact", head: true }).eq("category_id", id); if (count) redirect("/admin/categories?error=Category+is+used+by+recipes"); const { error } = await supabase.from("categories").delete().eq("id", id); if (error) redirect(`/admin/categories?error=${encodeURIComponent(error.message)}`); refresh(); redirect("/admin/categories?success=deleted"); }
export async function uploadRecipeImage(_state: ActionState, formData: FormData): Promise<ActionState> { await requireAdmin(); const file = formData.get("image"); if (!(file instanceof File) || !file.size) return { ok: false, message: "Choose an image." }; if (!["image/jpeg", "image/png", "image/webp", "image/avif"].includes(file.type)) return { ok: false, message: "Use JPEG, PNG, WebP, or AVIF." }; if (file.size > 5 * 1024 * 1024) return { ok: false, message: "Image must be 5MB or smaller." }; const ext = file.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${new Date().getUTCFullYear()}/${crypto.randomUUID()}.${ext}`; const supabase = await createClient(); const { error } = await supabase.storage.from("recipe-images").upload(path, file, { contentType: file.type, upsert: false }); if (error) return { ok: false, message: error.message }; const { data } = supabase.storage.from("recipe-images").getPublicUrl(path); return { ok: true, message: "Image uploaded.", imageUrl: data.publicUrl }; }
